<?php
/**
 * Implements hook_wysiwyg_editor_settings_alter()
 */
function wysiwyg_ckeditor_config_wysiwyg_editor_settings_alter(&$settings, $context) {
    // The $context variable contains information about the wysiwyg profile we're using
    // In this case we just need to check that the editor being used is ckeditor

    if ($context['profile']->editor == 'ckeditor') {

        // The $settings variable contains all the config options ckeditor uses. 
        // The array keys correspond directly with any setting that can be applied 
        // to CKEditor - as outlined in the CKEditor docs: 
        // http://docs.cksource.com/ckeditor_api/symbols/CKEDITOR.config.html 
        // Another way to override configuration is to use your own configuration javascript
        // file. In this case, we're going to add our own configuration file that will
        // Hold our stylesSet customizations... 
        $custom_path = base_path() . drupal_get_path('module', 'wysiwyg_ckeditor_config') .
            '/ckeditor_custom_config.js';
        $settings['customConfig'] = $custom_path;

        // To see what's in $settings and $context, install the devel module 
        // And run the variables through the dpm() function. 
    }
}
